steps:
  - name: "node"
    entrypoint: "npm"
    args: ["install"]
  # Build the frontend
  - name: "node"
    entrypoint: "npm"
    args: ["run", "build"]
    env:
      - "API_HOSTNAME=$_API_HOSTNAME"
  - id: "container_pull"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull gcr.io/$PROJECT_ID/${_CLOUD_RUN_APP_NAME}:latest || exit 0",
      ]
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["buildx", "build", "-t", "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME", "."]
  # Push the container image to Container Registry
  - id: "container_push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME"]
  # Deploy service for simple requests
  - waitFor:
    - container_push
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_CLOUD_RUN_APP_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME",
        "--region",
        "$_CLOUD_RUN_REGION",
        "--concurrency=40",
        "--cpu=1",
        "--memory=2Gi",
        "--set-env-vars",
        "LOGGING_FORMAT=gcp",
      ]
  # Deploy API service for high-intensity requests
  - waitFor:
    - container_push
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_CLOUD_RUN_HEAVY_DUTY_APP_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME",
        "--region",
        "$_CLOUD_RUN_REGION",
        "--concurrency=1",
        "--cpu=2",
        "--memory=8Gi",
        "--timeout=1200s",
        "--no-cpu-throttling",
        "--set-env-vars",
        "LOGGING_FORMAT=gcp"
      ]
timeout: 1800s
substitutions:
  _CLOUD_RUN_APP_NAME: "the-tuul"
  _CLOUD_RUN_HEAVY_DUTY_APP_NAME: "the-tuul-heavy-duty"
  _CLOUD_RUN_REGION: "us-central1"
  _API_HOSTNAME: "https://separate.the-tuul.com"
images:
  - gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME
